unified-prototype/build.gradle.kts
unified-prototype/settings.gradle.kts
unified-prototype/testbed-android-groovy/build.gradle
unified-prototype/testbed-android/build.gradle.kts
unified-prototype/testbed-kmp-groovy/build.gradle
unified-prototype/testbed-kmp/build.gradle.kts
unified-prototype/unified-plugin/gradle/libs.versions.toml
unified-prototype/unified-plugin/plugin-android/build.gradle.kts
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidLibrary.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidTarget.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/StandaloneAndroidLibraryPlugin.java
unified-prototype/unified-plugin/plugin-common/build.gradle.kts
unified-prototype/unified-plugin/plugin-common/src/main/java/org/gradle/api/experimental/common/LibraryDependencies.java
unified-prototype/unified-plugin/plugin-kmp/build.gradle.kts
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/AbstractKmpLibrary.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/KmpJsTarget.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/KmpJvmTarget.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/KmpTarget.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/KmpTargetContainer.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/StandaloneKmpLibraryPlugin.java

Implements minimal KMP and Android plugins.
Android targets are hard-coded
KMP targets are dynamic
Can declare common common dependencies and target-specific dependencies on both Android and KGP Can also declare common and taget-specific properties for both Android and KGP

Implement KMP and Android standalone plugins

---

unified-prototype/testbed-jvm-groovy/build.gradle
unified-prototype/testbed-jvm/build.gradle.kts
unified-prototype/testbed-jvm/src/common/java/com/example/Common.java
unified-prototype/testbed-jvm/src/common/java/com/example/Entrypoint.java
unified-prototype/testbed-jvm/src/common/java/com/example/Interface.java
unified-prototype/testbed-jvm/src/java11/java/com/example/Eleven.java
unified-prototype/testbed-jvm/src/java11/resources/META-INF/services/com.example.Interface
unified-prototype/testbed-jvm/src/java17/java/com/example/Seventeen.java
unified-prototype/testbed-jvm/src/java17/resources/META-INF/services/com.example.Interface
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/AbstractJvmLibrary.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/JavaTarget.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/JvmTarget.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/JvmTargetContainer.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/StandaloneJvmLibraryPlugin.java

This is a hack in that we create new features and then wire them into the main feature as targets. It works locally but the consumable configurations all have different capabilities even though they shouldn't.
Also this doesn't import into the IDE properly (red source files even though it compiles fine), since the IDE doesn't understand when a source file is part of more than one compilation.

Implement multi-target Jvm library plugin

---

unified-prototype/testbed-android-groovy/build.gradle
unified-prototype/testbed-android/build.gradle.kts
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidLibrary.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidTarget.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidTargets.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/StandaloneAndroidLibraryPlugin.java

This requires turning some interfaces into abstract classes to keep the Named implementation of AndroidTarget working.  It adds a new static AndroidTargets type that defines a Debug and Release target.

Replace the targets container with a static targets DSL block in the unified Android prototype

---

unified-prototype/gradle/wrapper/gradle-wrapper.properties
unified-prototype/testbed-android/build.gradle.something
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidLibrary.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidTarget.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidTargets.java
unified-prototype/unified-plugin/plugin-common/src/main/java/org/gradle/api/experimental/common/LibraryDependencies.java

The declarative DSL changes have been merged into Gradle proper, so we can depend on the nightly
* Update package names
* Update android testbed namespace since there not a kotlin and groovy version of the testbed anymore

Use latest nightly

---

unified-prototype/gradle/wrapper/gradle-wrapper.properties
unified-prototype/settings.gradle.kts
unified-prototype/testbed-android-application/build.gradle.something
unified-prototype/testbed-android-library/build.gradle.something
unified-prototype/testbed-kmp/build.gradle.something
unified-prototype/unified-plugin/plugin-android/build.gradle.kts
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidEcosystemPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/StandaloneAndroidApplicationPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/StandaloneAndroidLibraryPlugin.java
unified-prototype/unified-plugin/plugin-jvm/build.gradle.kts
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/JvmEcosystemPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/StandaloneJavaApplicationPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/StandaloneJvmLibraryPlugin.java
unified-prototype/unified-plugin/plugin-kmp/build.gradle.kts
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/KmpEcosystemPlugin.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/StandaloneKmpLibraryPlugin.java

This converts all prototype plugins to use software types and eco system plugins that can be applied at the settings level.

Convert prototype plugins to use software types

---

unified-prototype/unified-plugin/gradle/libs.versions.toml

This avoids some dependency issues when working with that project.

Downgrade versions to align with what was used in Now In Android

---

unified-prototype/README.md
unified-prototype/settings.gradle.kts
unified-prototype/testbed-java-application/build.gradle.something
unified-prototype/testbed-java-application/src/main/java/com/example/App.java
unified-prototype/testbed-java-library/build.gradle.something
unified-prototype/testbed-java-library/src/main/java/com/example/lib/Library.java
unified-prototype/unified-plugin/plugin-jvm/build.gradle.kts
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/JavaApplication.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/JavaComponent.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/JavaLibrary.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/StandaloneJavaApplicationPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/StandaloneJavaLibraryPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/JvmEcosystemPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/StandaloneJvmLibraryPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/internal/JvmPluginSupport.java

This PR adds a basic `javaLibrary` software type.
The PR also adds a `dependencies { }` block to both `javaLibrary` and `javaApplication` software types.

Add a `javaLibrary` software type.

---

unified-prototype/testbed-android-application/build.gradle.dcl
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/AndroidApplication.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/AndroidApplicationDependencies.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/StandaloneAndroidApplicationPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/AndroidLibrary.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/AndroidLibraryDependencies.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/CoreLibraryDesugaring.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/StandaloneAndroidLibraryPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/NiaSupport.java

- Auto-configure this if JDK > 8.
- Allow setting version of desugaring lib in new extension.
- Move to main Android lib/app from NiA-specific code.

Don't expose coreDesugaring conf

---

.github/workflows/cd.yml

I am not sure whether we need it or whether we will proceed with deployments to gradle.org, but staging it for preview/feedback
Preview: https://oleg-nenashev.github.io/declarative-gradle/

Add CD pipeline for the Declarative Gradle subsite

---

ROADMAP.md
docs/CONTRIBUTING.md

This PR changes the ROADMAP and CONTRIBUTING documents to only mention what's known.
We removed the links to the github project board because what's there is currently very much unrelated and we could not figure out where the milestone split and dates were coming from. The project board needs to be fixed before referencing it.

Clarify ROADMAP and co

---

docs/getting-started/README.md
docs/java/README.md
docs/kotlin/README.md
docs/swift/README.md
mkdocs.yml
unified-prototype/README.md
unified-prototype/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-android/build.gradle.kts
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidEcosystemPlugin.java
unified-prototype/unified-plugin/plugin-common/src/main/java/org/gradle/api/experimental/common/CliApplicationConventionsPlugin.java
unified-prototype/unified-plugin/plugin-common/src/main/java/org/gradle/api/experimental/common/HasCliExecutables.java
unified-prototype/unified-plugin/plugin-jvm/build.gradle.kts
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/JavaApplication.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/StandaloneJavaApplicationPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/JvmApplication.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/JvmEcosystemConventionsPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/JvmEcosystemPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/StandaloneJvmApplicationPlugin.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/KmpApplication.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/KmpEcosystemPlugin.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/StandaloneKmpApplicationPlugin.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kotlin/KotlinJvmApplication.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kotlin/StandaloneKotlinJvmApplicationPlugin.java
unified-prototype/unified-plugin/plugin-swift/src/main/java/org/gradle/api/experimental/swift/StandaloneSwiftApplicationPlugin.java
unified-prototype/unified-plugin/plugin-swift/src/main/java/org/gradle/api/experimental/swift/SwiftApplication.java

For software types that are implemented using Java or that target the JVM, define repositories so that the software can be built out-of-the-box without further configuration.
- Apply the foojay plugin.
- Add Maven central as a library repository.
- Also add the Google repo as a library repository when building Android software.
For software types that produce one or more CLI applications, add a `runAll` task (placeholder name) which will build and run the application for all target platforms and build types that can be built on the host machine.

Improve conventions for JVM software types and CLI application software types

---

unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AbstractAndroidSoftwarePlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidSoftware.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/AndroidApplication.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/StandaloneAndroidApplicationPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/Compose.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/CoreLibraryDesugaring.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/Hilt.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/KotlinSerialization.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/Room.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/testing/Jacoco.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/testing/Testing.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/AndroidLibrary.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/NiaSupport.java

- This will allow for setting an extension's properties and using enabled=false to NOT automatically apply the extension to every project of a particular software type.
- By default, with no explicit flag set, behavior remains the same.

Apply new pattern to convention extensions

---

unified-prototype/unified-plugin/internal-testing-utils/build.gradle.kts
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/integtests/fixtures/RepoScriptBlockUtil.groovy
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/AbstractSpecification.groovy
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/dsl/GradleDsl.groovy
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/file/AbstractTestDirectoryProvider.groovy
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/file/DoesNotSupportNonAsciiPaths.java
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/file/ExecOutput.groovy
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/file/LeaksFileHandles.java
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/file/TestDirectoryProvider.java
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/file/TestFile.java
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/file/TestFileHelper.groovy
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/file/TestNameTestDirectoryProvider.java
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/file/TestWorkspaceBuilder.groovy
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/testing/internal/util/RetryUtil.groovy
unified-prototype/unified-plugin/plugin-android/build.gradle.kts
unified-prototype/unified-plugin/plugin-android/src/integTest/groovy/org/gradle/api/experimental/android/AndroidLibrarySpec.groovy
unified-prototype/unified-plugin/settings.gradle.kts

- Set up an integration test suite that can apply the ecosystem plugin.
- Create an internal test utils lib containing many test file utils from gradle/gradle.
- Demo tests for applying the plugin with and without a convention.

Setup integration testing for Android Plugin

---

docs/android/README.md

Change documentation URL to point at https://github.com/gradle/nowinandroid repository.
- [core:common](https://github.com/gradle/nowinandroid/blob/main-declarative/core/common/build.gradle.dcl)
- [core:data](https://github.com/gradle/nowinandroid/blob/main-declarative/core/data/build.gradle.dcl)
- [core:domain](https://github.com/gradle/nowinandroid/blob/main-declarative/core/domain/build.gradle.dcl)
Fix #94

Fix documentation's broken URL.

---

unified-prototype/unified-plugin/gradle/libs.versions.toml
unified-prototype/unified-plugin/plugin-android/build.gradle.kts
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AbstractAndroidSoftwarePlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidSoftware.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidSoftwareBuildType.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidSupport.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/ProguardFile.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/AndroidApplication.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/StandaloneAndroidApplicationPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/BaselineProfile.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/BaselineProfileDependencies.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/Compose.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/Firebase.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/Licenses.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/testing/Jacoco.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/testing/Roborazzi.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/testing/Testing.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/AndroidLibrary.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/StandaloneAndroidLibraryPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/DimensionStrategy.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/Flavors.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/Licenses.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/NiaSupport.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/PrintApkLocationTask.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/package-info.java

Adds support for many new plugins:
- Proguard
- BaselineProfile
- Firebase
- GMS OSS Licenses
- Roborazzi
Fixes contentType to only be used in appropriate places, fully opt in for applications.
Support for various other minor flags used by NiA.
// Using TODO:DG for known limitations
**https://github.com/gradle/declarative-gradle/pull/90 should be merged first**

Add support for NiA :app project to use declarative syntax

---

unified-prototype/gradle/wrapper/gradle-wrapper.properties
unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/test/fixtures/AbstractSpecification.groovy
unified-prototype/unified-plugin/plugin-android/src/integTest/groovy/org/gradle/api/experimental/android/AndroidLibrarySpec.groovy
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidSoftware.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidSoftwareBuildType.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/AndroidApplication.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/BaselineProfile.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/Licenses.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/testing/Testing.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/AndroidLibrary.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/Feature.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/Flavors.java
unified-prototype/unified-plugin/plugin-common/src/main/java/org/gradle/api/experimental/common/extensions/Lint.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kotlin/KotlinJvmLibrary.java

- Removes auto-enable logic from @Configuring methods and makes all enabled flags @Restricted.
- Also adds simple integration test to demonstrate extension convention behavior.

Upgrade the Gradle wrapper to the latest nightly, requiring conventions to be explicitly enabled in projects

---

.devcontainer/requirements.txt
mkdocs.yml

Applies a fix for Python Markdown defaults so that we follow the GitHub Flavoured Markdown. https://github.com/Python-Markdown/markdown/issues/3

Fix default Markdown nested list indenting

---

unified-prototype/gradle/wrapper/gradle-wrapper.properties
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/StandaloneAndroidApplicationPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/StandaloneAndroidLibraryPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/StandaloneJavaApplicationPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/StandaloneJavaLibraryPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/StandaloneJvmApplicationPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/StandaloneJvmLibraryPlugin.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/StandaloneKmpApplicationPlugin.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/StandaloneKmpLibraryPlugin.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kotlin/StandaloneKotlinJvmApplicationPlugin.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kotlin/StandaloneKotlinJvmLibraryPlugin.java
unified-prototype/unified-plugin/plugin-swift/src/main/java/org/gradle/api/experimental/swift/StandaloneSwiftApplicationPlugin.java
unified-prototype/unified-plugin/plugin-swift/src/main/java/org/gradle/api/experimental/swift/StandaloneSwiftLibraryPlugin.java

As a follow up to https://github.com/gradle/gradle/pull/29648, this changes each prototype plugin to explicitly register the software type model object as a project extension.

Explicitly add software type model objects to extensions

---

unified-prototype/gradle/wrapper/gradle-wrapper.properties

The latest nightly includes support for applying build level conventions for software types in non-declarative scripts that apply software type plugins.

Update wrapper to latest Gradle nightly

---

docs/reference/software-features.md
unified-prototype/gradle/wrapper/gradle-wrapper.properties
unified-prototype/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-android/src/integTest/groovy/org/gradle/api/experimental/android/AndroidLibrarySpec.groovy

Updates to the latest nightly and handles the rename of `conventions { }` to `defaults { }`.

Update wrapper and rename conventions -> defaults

---

unified-prototype/unified-plugin/plugin-android-init/build.gradle.kts
unified-prototype/unified-plugin/plugin-android/build.gradle.kts
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidEcosystemPlugin.java

It doesn't seem necessary to apply the init plugin if you already have an android ecosystem project that is applying the ecosystem plugin.

Don't apply init plugin automatically from ecosystem plugin

---

.github/workflows/ci.yml
.github/workflows/preview-cleanup.yml

For https://github.com/gradle/community/issues/93 and the upcoming EAP 2 release

Add preview deployment and deletion pipelines

---

README.md
docs/ROADMAP.md
docs/getting-started/features.md
docs/getting-started/setup.md

IntelliJ IDEA builds with DCL support are now available at
https://drive.google.com/drive/folders/19iWu2F4dYs0Vc9xFMkSwY7wizKk-YMKl

Add IntelliJ IDEA to documentation

---

docs/getting-started/setup.md

Since yesterday one can simply download the latest Studio nightly
https://developer.android.com/studio/nightly

Android Studio regular nightlies now include support for Declarative

---

unified-prototype/unified-plugin/plugin-kmp/build.gradle.kts
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/StandaloneKmpApplicationPlugin.java

This is currently necessary for custom SoftwareTypes to reuse kotlinApplication extention as an inner extension and wire it.

All wiring KMP application plugin to kmpApplication block instance without applying plugin

---

unified-prototype/unified-plugin/internal-testing-utils/src/main/groovy/org/gradle/integtests/fixtures/AbstractBuildInitSpecification.groovy
unified-prototype/unified-plugin/plugin-android-init/src/integTest/groovy/org/gradle/api/experimental/android/AndroidApplicationAgpPreview.groovy
unified-prototype/unified-plugin/plugin-android-init/src/integTest/groovy/org/gradle/api/experimental/android/AndroidApplicationAgpPreviewBuildInitSpec.groovy
unified-prototype/unified-plugin/plugin-android-init/src/main/resources/templates/android-application-basic-activity/app/build.gradle.dcl
unified-prototype/unified-plugin/plugin-android-init/src/main/resources/templates/android-application-basic-activity/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-android-init/src/main/resources/templates/android-application-empty-activity/app/build.gradle.dcl
unified-prototype/unified-plugin/plugin-android-init/src/main/resources/templates/android-application-empty-activity/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-android-init/src/main/resources/templates/android-application/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-jvm/src/main/resources/templates/java-application/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-kmp/src/main/resources/templates/kotlin-application/settings.gradle.dcl

This should ensure we keep the build init specs up-to-date with the latest published version.
It will make the first build after publishing a new version fail, but that should be an easy update.
**Rebase this on master after merging Gradle-plugin-plugin support**

Update init build specs in prototype; add check to verify version used remains curent
