README.md

Just started the README to collect and channel feedback

Add README and a very basic concept from examples

---

README.md

Add link to Gradle forums

---

LICENSE.txt
README.md
docs/CONTRIBUTING.md
early-prototypes/README.md
unified-prototype/README.md

Closes #17 
- Added license
- Added overview and explicit status
- Set expectations about the current status

Declarative Gradle README updates

---

unified-prototype/testbed-android-application/build.gradle.something
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/AndroidApplication.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/StandaloneAndroidApplicationPlugin.java

Adds support for versionCode, versionName, applicationId at the top-level

Add support for new android application fields

---

unified-prototype/android-util/build.gradle.something
unified-prototype/android-util/src/main/kotlin/com/example/Utils.kt
unified-prototype/gradle/wrapper/gradle-wrapper.properties
unified-prototype/settings.gradle.kts
unified-prototype/testbed-android-application/build.gradle.something
unified-prototype/testbed-android-application/src/debug/kotlin/com/example/BufferMakerImpl.kt
unified-prototype/testbed-android-application/src/main/kotlin/com/example/MyApp.kt
unified-prototype/testbed-android-application/src/release/kotlin/com/example/BufferMakerImpl.kt
unified-prototype/testbed-android-library/build.gradle.something
unified-prototype/testbed-android-library/src/main/kotlin/com/example/MyLib.kt

Completes milestone ["Can add a project dependency to an Android application and library - STARTED"](https://docs.google.com/document/d/1DqSriCam1MtUYq00LzuA9RfTnnlTtx_lUA6yG7yXcac/edit#heading=h.33novdwauh2a)

Demonstrate project dependencies in Android testbed projects

---

unified-prototype/build.gradle.kts
unified-prototype/gradle.properties
unified-prototype/unified-plugin/gradle/libs.versions.toml
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/StandaloneJavaApplicationPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/java/StandaloneJavaLibraryPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/StandaloneJvmLibraryPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/internal/JvmPluginSupport.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/internal/KotlinPluginSupport.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kotlin/StandaloneKotlinJvmApplicationPlugin.java
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kotlin/StandaloneKotlinJvmLibraryPlugin.java

This PR is a bucket of minor refactors and changes. See the commit messages for more details.

Some polishing

---

unified-prototype/testbed-android-library/build.gradle.dcl
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/AndroidLibraryDependencies.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/AndroidTestDependencies.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/StandaloneAndroidLibraryPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/Testing.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/NiaSupport.java

- Migrate testing deps definition to new testing deps block

Migrate some Android dependency declarations to new more specific sub blocks

---

unified-prototype/gradle/wrapper/gradle-wrapper.properties
unified-prototype/testbed-android-application/build.gradle.dcl
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/StandaloneAndroidLibraryPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/NiaSupport.java

- Only apply NiASupport for NiA project - adjust expectations of non-NiA Android test projects.

Make ready for declarative conventions in NiA

---

mkdocs.yml

Remove "subsite" from the site description

---

.devcontainer/requirements.txt
docs/java/README.md
docs/kotlin/README.md
mkdocs.yml

Just stubs for now, but we will keep expanding

Add stub Java and Kotlin pages

---

unified-prototype/unified-plugin/gradle/libs.versions.toml
unified-prototype/unified-plugin/plugin-android/build.gradle.kts
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AbstractAndroidSoftwarePlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidSoftware.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/StandaloneAndroidApplicationPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/Room.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/testing/TestOptions.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/StandaloneAndroidLibraryPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/NiaSupport.java

- Add testInstrumentationRunner property to testOptions
- Setup Room feature extension and support

Supports Additional properties and conventions for testing and Room

---

unified-prototype/unified-plugin/gradle/libs.versions.toml
unified-prototype/unified-plugin/plugin-android/build.gradle.kts
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/AndroidApplication.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/application/StandaloneAndroidApplicationPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/DependencyGuard.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/CheckBadgingTask.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/GenerateBadgingTask.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/nia/NiaSupport.java

- Add extension for DependencyGuard support.
- Remove unnecessary contentType configuration for Android applications.
- Reorganize Version Catalog.

Add support for NiA :app-nia-catalog project to use declarative syntax

---

.gitignore
unified-prototype/testbed-kotlin-application/build.gradle.dcl
unified-prototype/testbed-kotlin-library/build.gradle.dcl
unified-prototype/unified-plugin/gradle/libs.versions.toml
unified-prototype/unified-plugin/plugin-android/build.gradle.kts
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AbstractAndroidSoftwarePlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/AndroidSoftware.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/extensions/Secrets.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/AndroidLibrary.java
unified-prototype/unified-plugin/plugin-android/src/main/java/org/gradle/api/experimental/android/library/StandaloneAndroidLibraryPlugin.java
unified-prototype/unified-plugin/plugin-android/src/main/resources/templates/android-application-basic-activity/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-android/src/main/resources/templates/android-application-empty-activity/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-android/src/main/resources/templates/android-application/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-jvm/src/main/resources/templates/java-application/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-kmp/src/main/resources/templates/kotlin-application/settings.gradle.dcl

- Add buildConfig feature flag
- Update AGP to 8.7.1 (fixes IDE sync in latest AS)
- Update kotlinx-datetime version in testbed projects
- Add Secrets feature to support Gradle Secrets Plugin

Updates for work on Now In Android

---

unified-prototype/unified-plugin/plugin-android-init/src/main/java/org/gradle/api/experimental/android/AndroidEcosystemInitPlugin.java
unified-prototype/unified-plugin/plugin-android-init/src/main/resources/templates/android-application-basic-activity/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-android-init/src/main/resources/templates/android-application-empty-activity/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-android-init/src/main/resources/templates/android-application/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-common/src/integTest/groovy/org/gradle/util/ResourceLoaderIntegrationTest.groovy
unified-prototype/unified-plugin/plugin-common/src/main/java/org/gradle/api/experimental/buildinit/StaticBuildGenerator.java
unified-prototype/unified-plugin/plugin-common/src/main/java/org/gradle/api/experimental/buildinit/StaticBuildSpec.java
unified-prototype/unified-plugin/plugin-common/src/main/java/org/gradle/util/ResourceLoader.java
unified-prototype/unified-plugin/plugin-common/src/test/groovy/org/gradle/util/ResourceLoaderTest.groovy
unified-prototype/unified-plugin/plugin-common/src/testFixtures/groovy/org/gradle/test/util/TestAssertions.groovy
unified-prototype/unified-plugin/plugin-jvm/src/main/java/org/gradle/api/experimental/jvm/JvmEcosystemInitPlugin.java
unified-prototype/unified-plugin/plugin-jvm/src/main/resources/templates/java-application/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-kmp/src/main/java/org/gradle/api/experimental/kmp/KmpEcosystemInitPlugin.java
unified-prototype/unified-plugin/plugin-kmp/src/main/resources/templates/kotlin-application/settings.gradle.dcl

- Simplify test logic and de-duplicate assertions.

Fix generator and tests on Windows

---

.github/workflows/ci.yml
.github/workflows/preview-cleanup.yml

Use better Preview site destination

---

docs/ROADMAP.md

Prettify the Roadmap disclaimer

---

unified-prototype/unified-plugin/gradle/libs.versions.toml

- Make compatible with latest Android Studio.
- Remove warnings from build and in IntelliJ.

Update AGP, Kotlin, and other deps

---

docs/publications/README.md

Add more Declarative Gradle articles, split official and community posts

---

unified-prototype/unified-plugin/plugin-android-init/build.gradle.kts
unified-prototype/unified-plugin/plugin-android-init/src/main/resources/templates/android-application-basic-activity/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-android-init/src/main/resources/templates/android-application-empty-activity/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-android-init/src/main/resources/templates/android-application/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-android/build.gradle.kts
unified-prototype/unified-plugin/plugin-common/build.gradle.kts
unified-prototype/unified-plugin/plugin-jvm/build.gradle.kts
unified-prototype/unified-plugin/plugin-jvm/src/main/resources/templates/java-application/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-kmp/build.gradle.kts
unified-prototype/unified-plugin/plugin-kmp/src/main/resources/templates/kotlin-application/settings.gradle.dcl
unified-prototype/unified-plugin/plugin-plugin/build.gradle.kts

Also update version of prototype used in testing

Integration tests use version file for up-to-date checking

---

mkdocs.yml

* Follows up https://github.com/gradle/declarative-gradle/pull/187

Add migration guide and case study to the navigation

---

mkdocs.yml

For https://github.com/gradle/bt-devrel-and-education/issues/84 (internal link)

Add a note on the trademarks

---

unified-prototype/unified-plugin/plugin-common/src/integTest/groovy/org/gradle/util/ResourceLoaderIntegrationTest.groovy
unified-prototype/unified-plugin/plugin-common/src/main/java/org/gradle/util/ResourceLoader.java

Fix zipslip issue in ResourceLoader
